project:
  type: website
  output-dir: docs
  resources: [images, fr-hes/png]

lang: en

# Config
website:
  title: "FastForest / Home"
  description: "Website of the FastForest group of Silva @ INRAE Grand Est - Nancy"
  site-url: http://mcuntz.github.io/fastforest/
  repo-url: https://github.com/mcuntz/fastforest
  favicon: images/fastforest_logo.png
  #  sidebar: not nice
  #    contents: auto
  ## Navbar menu
  navbar:
    logo: images/fastforest_logo.png
    ## left-hand-side of navbar
    left:
      # - text: Home
      #   icon: house-door
      #   href: index.qmd
      - text: Projects
        icon: puzzle
        menu:
          - text: "Current projects"
            href: projects/current.qmd
          - text: "PHydrauCC"
            href: projects/phydraucc.qmd
          - text: "SlowStom"
            href: projects/slowstom.qmd
          - text: "TAW-tree"
            href: projects/taw-tree.qmd
          - text: "LSMxAI"
            href: projects/lsmxai.qmd
          - text: "DroughtForC"
            href: projects/droughtforc.qmd
          - text: "EuropeDrought"
            href: projects/europedrought.qmd
      - text: People
        icon: people
        menu:
          - text: "Research Group"
            href: people/group.qmd
          - text: "Alwin Naiken"
            href: people/alwin_naiken.qmd
          - text: "Gabriel Destouet"
            href: people/gabriel_destouet.qmd
          - text: "Matthias Cuntz"
            href: people/matthias_cuntz.qmd
          - text: "Sylvain Faller"
            href: people/sylvain_faller.qmd
          - text: "Yasin Gundesli"
            href: people/yasin_gundesli.qmd
          - text: "Zihan Lu"
            href: people/zihan_lu.qmd
      - text: FR-Hes
        icon: tree
        menu:
          - text: "ICOS website"
            href: https://meta.icos-cp.eu/resources/stations/ES_FR-Hes
          - text: "Current data"
            href: fr-hes/current_data.qmd
      - text: Tools
        icon: gear
        menu:
          - text: "Overview"
            href: tools/overview.qmd
          - text: Data viewer
            href: "/tools/overview.html#sec-data-viewer"
          - text: Eddy covariance
            href: "/tools/overview.html#sec-eddy-covariance"
          - text: Python tools
            href: "/tools/overview.html#sec-python-tools"
          - text: Other tools
            href: "/tools/overview.html#sec-other-tools"
    ## right-hand-side of navbar
    right:
      - icon: globe
        menu:
          - text: Quarto
            href: https://quarto.org
          - text: inrae-project-website
            href: https://github.com/SebastienBoutry/inrae-project-website
      - icon: github
        href: https://www.github.com/mcuntz/fastforest
  ## Footer
  page-footer:
    left: |
      ![](/images/Republique_Francaise_RVB.png){width=100px} &nbsp; [![](/images/Logo-INRAE_Transparent.png){width=100px}](https://www.inrae.fr/)
    center:
      - text: Legal Notice
        icon: book
        href: legal_notice.qmd
    right: |
      [![](/images/Logo_UMR_Silva-petit.png){width=100px}](https://silva.nancy.hub.inrae.fr/)
  ## Margin
  margin-footer: |

format:
  html:
    theme:
      light: default
      dark: darkly
    respect-user-color-scheme: true
    css: resources/styles.css
    toc: true
    # grid:
    #   sidebar-width: 50px
    #   body-width: 1150px
    #   margin-width: 300px
    #   gutter-width: 1.5rem
    grid:
      sidebar-width: 10px
      body-width: 1080px
      margin-width: 150px
      gutter-width: 1.5rem
