project:
  type: website
  output-dir: docs
  # resources: images
  resources: [images, fr-hes/png]

# Set language
lang: en

# Set website config and logos
website:
  title: "FastForest / Home"
  description: "Website of the FastForest group of Silva @ INRAE Grand Est - Nancy"
  site-url: http://mcuntz.github.io/
  repo-url: https://github.com/mcuntz/mcuntz.github.io
  #  sidebar: not nice
  #    contents: auto
  ## Navbar menu
  navbar:
    logo: images/fastforest_logo.png
    left:
      # - text: Home
      #   icon: house-door
      #   href: index.qmd
      - text: Projects
        icon: puzzle
        menu:
          - text: "Current projects"
            href: projects/current.qmd
          - text: "PHydrauCC"
            href: projects/phydraucc.qmd
          - text: "SlowStom"
            href: projects/slowstom.qmd
          - text: "TAW-tree"
            href: projects/taw-tree.qmd
          - text: "LSMxAI"
            href: projects/lsmxai.qmd
          - text: "DroughtForC"
            href: projects/droughtforc.qmd
          - text: "EuropeDrought"
            href: projects/europedrought.qmd
      - text: People
        #href: people/index.qmd
        icon: people
        menu:
          - text: "Emilie Joetzjer"
            href: people/emilie_joetzjer.qmd
          - text: "Gabriel Destouet"
            href: people/gabriel_destouet.qmd
          - text: "Matthias Cuntz"
            href: people/matthias_cuntz.qmd
          - text: "Zihan Lu"
            href: people/zihan_lu.qmd
      - text: FR-Hes
        icon: tree
        menu:
          - text: "ICOS website"
            href: fr-hes/icos.qmd
          - text: "Current data"
            href: fr-hes/current_data.qmd
    tools:
      - text: "Other links"
        icon: globe
        menu:
          - text: inrae-project-website
            href: https://github.com/SebastienBoutry/inrae-project-website
          - text: Quarto
            href: https://quarto.org
      - text: "Source"
        icon: github
        href: https://www.github.com/mcuntz/mcuntz.github.io
  ## Footer
  page-footer:
    left: |
      [![](/images/Republique_Francaise_RVB.png){width=100px}![](/images/Logo-INRAE_Transparent.png){width=100px}](https://www.inrae.fr/)
    center:
      - text: LEGAL NOTICE
        icon: book
        href: legal_notice.qmd
    right: |
      [![](/images/Logo_UMR_Silva-petit.png){width=100px}](https://silva.nancy.hub.inrae.fr/)
  ## Margin
  margin-footer: |

format:
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
  html:
    theme:
      light: default
      dark: darkly
    respect-user-color-scheme: true
    css: resources/styles.css
    toc: true
    grid:
      sidebar-width: 50px
      body-width: 1150px
      margin-width: 300px
      gutter-width: 1.5rem
