## Legal Notices

(informative sites with no paid content or services)

### Site Identification

Site name: FastForest<br>
Full site URL: https://mcuntz.github.io/


### Site Publisher

French National Research Institute for Agriculture, Food and Environment (INRAE)<br>
INRAE is a public scientific and technical establishment headquartered at 147, rue de l’Université – 75338 Paris CEDEX 07.
Its statutes are published in the French rural and maritime fishing code (Code rural et de la pêche maritime) (Articles R831-1 et seq.)<br>
It is represented by its President, Mr Philippe Mauguin.<br>
Email contact: web@inrae.fr - Telephone: 01 42 75 00 00


### Identification Numbers

INRAE<br>
SIREN: 180070039<br>
Code APE: 7219Z<br>
Intra-community VAT number: FR 57 1800700039


### Site Publication

Name of the Publication Director: Mr Philippe MAUGUIN<br>
Name of the Publication Manager: Mr Matthias Cuntz INRAE Research Director<br>
Webmaster: Mr Matthias Cuntz INRAE Research Director


### Site Host

INRAE<br>
Public scientific and technical establishment<br>
147, rue de l'Université - 75338 Paris cedex 07<br>
01 42 75 90 00
