---
---

## Research group

### Current members

<hr>

- [**Alwin Naiken**](alwin_naiken.qmd), Ingénieur d'Études &nbsp; &nbsp; <a href="mailto:alwin.naiken@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](alwin_naiken.qmd)

- [**Emilie Joetzjer**](emilie_joetzjer.qmd), Chargée de Recherche &nbsp; &nbsp; [{{< fa brands google >}} Scholar](https://scholar.google.com/citations?user=HbGvaIIAAAAJ&hl=fr) &nbsp; &nbsp; [{{< fa brands bluesky >}}](https://bsky.app/profile/e-joetzjer.bsky.social) &nbsp; &nbsp; <a href="mailto:emilie.joetzjer@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](emilie_joetzjer.qmd)

- [**Gabriel Destouet**](gabriel_destouet.qmd), Postdoc &nbsp; &nbsp; [{{< fa brands orcid >}}](https://orcid.org/0000-0001-5402-126X) &nbsp; &nbsp; <a href="mailto:gabriel.destouet@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](gabriel_destouet.qmd)

- **Hashwek Thillaigovindan Ramesh**, Master Student

- [**Matthias Cuntz**](matthias_cuntz.qmd), Directeur de Recherche &nbsp; &nbsp; [{{< fa brands google >}} Scholar](https://scholar.google.com/citations?user=s93VuhMAAAAJ) &nbsp; &nbsp; [{{< fa brands bluesky >}}](https://bsky.app/profile/mcuntz.bsky.social) &nbsp; &nbsp; <a href="mailto:matthias.cuntz@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](matthias_cuntz.qmd)

- **Pascal Courtois**, Technician &nbsp; &nbsp; <a href="mailto:pascal.courtois@inrae.fr">{{< fa solid envelope >}}</a>

- [**Rumeng He**](rumeng_he.qmd), PhD Student &nbsp; &nbsp; <a href="mailto:rumeng.he@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](rumeng_he.qmd)

- [**Sylvain Faller**](sylvain_faller.qmd), PhD Student &nbsp; &nbsp; <a href="mailto:sylvain.faller@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](sylvain_faller.qmd)

- [**Yasin Gundesli**](yasin_gundesli.qmd), PhD Student &nbsp; &nbsp; <a href="mailto:yasin.gundesli@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](yasin_gundesli.qmd)

- [**Zihan Lu**](zihan_lu.qmd), Postdoc &nbsp; &nbsp; <a href="mailto:zihan.lu@inrae.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](zihan_lu.qmd)

<hr>

### Former members

<hr>

- **Anaïs Thomas**, Postdoc &nbsp; &nbsp; <a href="mailto:anais.grosjean@univ-lorraine.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](https://www.lae.univ-lorraine.fr/fr/membre/anais-thomas)

- **Emilie Jeanpierre**, Master student

- **Fabio Gennaretti**, Postdoc &nbsp; &nbsp; [{{< fa brands google >}} Scholar](https://scholar.google.com/citations?user=oxRo7KkAAAAJ) &nbsp; &nbsp; <a href="mailto:f.gennaretti@univpm.it">{{< fa solid envelope >}}</a>

- **Hugues Clivot**, Postdoc &nbsp; &nbsp; <a href="mailto:hugues.clivot@univ-reims.fr">{{< fa solid envelope >}}</a> &nbsp; &nbsp; [{{< fa solid globe >}}](https://fare.nancy.hub.inrae.fr/trombinoscope/personnel-permanent/clivot-hugues)

- **James Ryder**, Postdoc

- **Jean-Baptiste Lily**, Ingénieur d'études

- **Jérémy Mauer**, Ingénieur d'études

- **Julie Sonzogni**, Master student

- **Julien Sainte-Marie**, Postdoc &nbsp; &nbsp; [{{< fa brands google >}} Scholar](https://scholar.google.com.au/citations?user=8RL87RsAAAAJ) &nbsp; &nbsp; <a href="mailto:julien.sainte-marie@agroparistech.fr">{{< fa solid envelope >}}</a>

- **Laura Fernández de Uña**, Postdoc &nbsp; &nbsp; [{{< fa brands google >}} Scholar](https://scholar.google.es/citations?user=u1J5Jz8AAAAJ)

- **Mohamed Ibrahim Belaid**, Master student

- **Mung Htoi Aung**, Master student

- **Thomas Aiguier**, Ingénieur d'études

<hr>
